### ISSUE TITLE
API Server Deployment

### ISSUE THREAD

**Issue by ofpiyush** [IndiaVaccineIN/api_server#17]

**Comment by g-savitha** [comment]
Can you be more specific about this issue? On which platform does it have to be deployed?

**Comment by ofpiyush** [comment]
Hola @g-savitha!

At the time of opening this issue, we were using cards on https://github.com/IndiaVaccineIN/api_server/projects/1 and most of the conversation was on the indiavaccine discord.

Sorry for the lack of details. We didn't have much details back then ourselves. The server is on EKS.

We still have to set up the build pipeline. If you want to take that we can convert that card into an issue and jump in!

Hop on over to https://indiavaccine.in to get invited to the discord.
